# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/aes_block_diagram/aes_block_diagram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_block_diagram || ORIG_REF_NAME==aes_block_diagram} -quiet] -quiet

# IP: bd/aes_block_diagram/ip/aes_block_diagram_processing_system7_0_0/aes_block_diagram_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_block_diagram_processing_system7_0_0 || ORIG_REF_NAME==aes_block_diagram_processing_system7_0_0} -quiet] -quiet

# IP: bd/aes_block_diagram/ip/aes_block_diagram_myip_0_0/aes_block_diagram_myip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_block_diagram_myip_0_0 || ORIG_REF_NAME==aes_block_diagram_myip_0_0} -quiet] -quiet

# IP: bd/aes_block_diagram/ip/aes_block_diagram_auto_pc_0/aes_block_diagram_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_block_diagram_auto_pc_0 || ORIG_REF_NAME==aes_block_diagram_auto_pc_0} -quiet] -quiet

# IP: bd/aes_block_diagram/ip/aes_block_diagram_ps7_0_axi_periph_0/aes_block_diagram_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_block_diagram_ps7_0_axi_periph_0 || ORIG_REF_NAME==aes_block_diagram_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/aes_block_diagram/ip/aes_block_diagram_rst_ps7_0_100M_0/aes_block_diagram_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_block_diagram_rst_ps7_0_100M_0 || ORIG_REF_NAME==aes_block_diagram_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/gianluca/OS_project/OS_project.gen/sources_1/bd/aes_block_diagram/aes_block_diagram_ooc.xdc
