# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.srcs/sources_1/bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0.xci
# IP: The module: 'hw_platform_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.gen/sources_1/bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_platform_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.gen/sources_1/bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_platform_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.gen/sources_1/bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_platform_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.srcs/sources_1/bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0.xci
# IP: The module: 'hw_platform_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.gen/sources_1/bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_platform_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.gen/sources_1/bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_platform_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.gen/sources_1/bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_platform_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
