# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw_platform/hw_platform.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_platform || ORIG_REF_NAME==hw_platform} -quiet] -quiet

# IP: bd/hw_platform/ip/hw_platform_processing_system7_0_0/hw_platform_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_platform_processing_system7_0_0 || ORIG_REF_NAME==hw_platform_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw_platform/ip/hw_platform_aes_axi_ip_if_0_0/hw_platform_aes_axi_ip_if_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_platform_aes_axi_ip_if_0_0 || ORIG_REF_NAME==hw_platform_aes_axi_ip_if_0_0} -quiet] -quiet

# IP: bd/hw_platform/ip/hw_platform_auto_pc_0/hw_platform_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_platform_auto_pc_0 || ORIG_REF_NAME==hw_platform_auto_pc_0} -quiet] -quiet

# IP: bd/hw_platform/ip/hw_platform_ps7_0_axi_periph_0/hw_platform_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_platform_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw_platform_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw_platform/ip/hw_platform_rst_ps7_0_100M_0/hw_platform_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_platform_rst_ps7_0_100M_0 || ORIG_REF_NAME==hw_platform_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/riccardo/git/aes-cryptocore/hw_platform_300923/hw_platform/hw_platform.gen/sources_1/bd/hw_platform/hw_platform_ooc.xdc
