/*  aes-core-driver.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>


#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#include <linux/fs.h>               // Header for the Linux file system support
#include <linux/uaccess.h>          // Required for the copy to user function


#define BASE_ADDR 			(0x43C00000U)

#define OFFSET_STATUS_0 	(0x00000000U) 
#define OFFSET_STATUS_1 	(0x00000004U)
#define OFFSET_STATUS_2 	(0x00000008U)
#define OFFSET_STATUS_3 	(0x0000000CU)

#define OFFSET_KEY_0    	(0x00000010U)
#define OFFSET_KEY_1    	(0x00000014U)
#define OFFSET_KEY_2    	(0x00000018U)
#define OFFSET_KEY_3    	(0x0000001CU)

#define OFFSET_OUTPUT_0 	(0x00000020U)
#define OFFSET_OUTPUT_1 	(0x00000024U)
#define OFFSET_OUTPUT_2 	(0x00000028U)
#define OFFSET_OUTPUT_3 	(0x0000002CU)

#define DEST_ADDR(x,y)      (void __iomem*)((size_t)(x) + (size_t)(y))

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("aes-core-driver - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "aes-core-driver"
#define  CLASS_NAME "core"           ///< The device class -- this is a character device driver
#define DEVICE_NAME "aes-core"

//static char ker_buf[100];
//static int *result;
static int    majorNumber;                  ///< Stores the device number -- determined automatically
static struct class *driver_class = NULL;
static dev_t ldev;
static struct device *ourdev;


/** ptrs to the I/O regs */
static uint32_t local_buf       = 0U;
static void __iomem *vi_baddr   = NULL;
static uint32_t* baddrloc 		= NULL;



/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct aes_core_driver_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

/* Functions prototype */

static int dev_open(struct inode *inod, struct file *fil);
static int dev_close(struct inode *inod, struct file *fil);
static ssize_t dev_read(struct file *fp, char *buf, size_t len, loff_t *off);
static ssize_t dev_write(struct file *fp, const char *user_buf, size_t len, loff_t *off);


static struct file_operations fops = {
    .read    = dev_read,
	.write   = dev_write,
    .open    = dev_open,
	.release = dev_close, 
};




static irqreturn_t aes_core_driver_irq(int irq, void *lp)
{
	printk("aes-core-driver interrupt\n");
	return IRQ_HANDLED;
}

static int aes_core_driver_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct aes_core_driver_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct aes_core_driver_local *) kmalloc(sizeof(struct aes_core_driver_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate aes-core-driver device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "aes-core-driver: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	// added by us (simple device registration)
 printk (KERN_INFO "LM: Initializing the LMODULE LKM !!\n");


   /* Major number, so you associate the driver with the special file of VFS */
   // Try to dynamically allocate a major number for the device -- more difficult but worth it
   majorNumber = register_chrdev(0, DEVICE_NAME, &fops);

   if (majorNumber < 0)
   {
       printk (KERN_ALERT "failed to register a major number\n");
       return majorNumber;
   }

   /* Now this driver is associated with a major number */
   printk (KERN_INFO "registered correctly with major number %d\n", majorNumber);


   /* The class is needed. Register device class */
   driver_class = class_create(THIS_MODULE, CLASS_NAME);

   if (IS_ERR(driver_class))
   {                // Check for error and clean up if there is
       unregister_chrdev(majorNumber, DEVICE_NAME);
       printk(KERN_ALERT "Failed to register device class\n");
       return PTR_ERR(driver_class);          // Correct way to return an error on a pointer
   }

   printk(KERN_INFO "LM: device class registered correctly\n");
 
   /* Once you have the major number, device class, you need to register the device --> device_create */

   ourdev = device_create(driver_class, NULL, MKDEV(majorNumber, 0), NULL, DEVICE_NAME);

   /* Error control is MANDATORY for device drivers */
   if (IS_ERR(ourdev))
   {               // Clean up if there is an error
       class_destroy(driver_class);           // Repeated code but the alternative is goto statements
       unregister_chrdev(majorNumber, DEVICE_NAME);
       printk(KERN_ALERT "Failed to create the device\n");
       return PTR_ERR(ourdev);
   }

   printk (KERN_INFO "LM: device class created correctly\n"); // Made it! device was initialized


	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		vi_baddr = lp->base_addr;  
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "aes-core-driver at 0x%08x mapped to 0x%08x and local is: 0x%08x \n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr,
			(unsigned int __force)vi_baddr);
		
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &aes_core_driver_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	//vi_baddr = ioremap(BASE_ADDR, 0xFFU);
	//vi_baddr = lp->base_addr;  


	dev_info(dev,"aes-core-driver at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int aes_core_driver_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct aes_core_driver_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id aes_core_driver_of_match[] = {
	{ .compatible = "xlnx,aes-axi-ip-if-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, aes_core_driver_of_match);
#else
# define aes_core_driver_of_match
#endif


static struct platform_driver aes_core_driver_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= aes_core_driver_of_match,
	},
	.probe		= aes_core_driver_probe,
	.remove		= aes_core_driver_remove,
};



static int __init aes_core_driver_init(void)
{
	printk("<1>AES CRYPTO-CORE DEVICE DRIVER INIT\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);

	
	baddrloc = ioremap(BASE_ADDR, 0xFFU);

	printk("<1>The local ioremap baddrloc stores: (0x%x)\n", baddrloc);
	printk("<1>The vi_baddr stores: (0x%x)\n", (uint32_t*)vi_baddr);


	return platform_driver_register(&aes_core_driver_driver);
}


static ssize_t dev_read
(
	struct file *fp, 
	char *buf, 
	size_t len, 
	loff_t *off
)
{
	struct aes_core_driver_local *lp = dev_get_drvdata(fp->f_inode->i_private);
	uint32_t *baddr = lp->base_addr;
	uint32_t *addr = DEST_ADDR(baddr, *off);
	uint8_t err = 0U;

	printk(KERN_ALERT "Device starting to read");
	uint32_t value = readl(addr);
	
	err = copy_to_user(buf, &value, sizeof(value));
	if (err != 0U)
	{
		printk(KERN_ALERT "ERROR_R: impossible to copy to user space");
	}
	
	printk(KERN_ALERT "Succesfully read: data %0X", local_buf);
	

  	return 0;

}

static ssize_t dev_write
(
	struct file *fp,
	const char *user_buf,
	size_t len,
	loff_t *off
)
{
	uint8_t  err        = 0U;
	

	//printk(KERN_ALERT "device starting to write");
	//printk(KERN_ALERT "Write function.\nVirtual address = %08X\n local_buf = %08X\n", vi_baddr, local_buf);
	//printk(KERN_ALERT "user_buf = %08X\n", *user_buf);
	struct aes_core_driver_local *lp = dev_get_drvdata(fp->f_inode->i_private);
  	uint32_t *baddr = lp->base_addr;

  	// Determine the address to write to based on the offset
  	uint32_t *addr = DEST_ADDR(baddr, *off);

	  // Verify that the length of data to write is equal to the size of the register
  	if (len != sizeof(uint32_t)) {
  	  return -EINVAL;
  	}

	uint32_t value;
	err = copy_from_user(&value, user_buf, len);
	if (err != 0U)
	{
		printk(KERN_ALERT "ERROR_W: impossible to copy from user space");
	}
	
	
	//writel(local_buf,DEST_ADDR(vi_baddr,*off));

	writel(value,addr);

	printk(KERN_ALERT "Succesfully write: data %s", local_buf);
	
	return 0;
}

static int dev_close(struct inode *inod, struct file *fil){
	printk(KERN_ALERT "device closed\n");
	return 0;
}


static void __exit aes_core_driver_exit(void)
{
	platform_driver_unregister(&aes_core_driver_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

static int dev_open(struct inode *inod, struct file *fil){
	printk(KERN_ALERT "device opened");

	//printk(KERN_ALERT "Open function.\nVirtual address = %08X\n local_buf = %08X\n", vi_baddr, local_buf);
	return 0;
}

module_init(aes_core_driver_init);
module_exit(aes_core_driver_exit);
