# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gianluca/OS_project/OS_project.srcs/sources_1/bd/aes_block_diagram/ip/aes_block_diagram_auto_pc_0/aes_block_diagram_auto_pc_0.xci
# IP: The module: 'aes_block_diagram_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gianluca/OS_project/OS_project.gen/sources_1/bd/aes_block_diagram/ip/aes_block_diagram_auto_pc_0/aes_block_diagram_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_block_diagram_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gianluca/OS_project/OS_project.srcs/sources_1/bd/aes_block_diagram/ip/aes_block_diagram_auto_pc_0/aes_block_diagram_auto_pc_0.xci
# IP: The module: 'aes_block_diagram_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gianluca/OS_project/OS_project.gen/sources_1/bd/aes_block_diagram/ip/aes_block_diagram_auto_pc_0/aes_block_diagram_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_block_diagram_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
